# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.

mqttDevice.id =  - Required. An identifier that uniquely identifies the device in the device event and device command MQTT topic namespaces.
mqttDevice.topic.prefix = - A optional prefix that by default is used when composing device event and command MQTT topics, and the client's MQTT clientId. The default is no prefix.
mqttDevice.event.topic.pattern - Optional. The topic pattern used for MQTT device event topics. Defaults to {mqttDevice.topic.prefix}id/{mqttDevice.id}/evt/{EVENTID}/fmt/json The pattern must include {EVENTID} and must end with "/fmt/json".
mqttDevice.command.topic.pattern - Optional. The topic pattern used for MQTT device command topics. Defaults to {mqttDevice.topic.prefix}id/{mqttDevice.id}/cmd/{COMMAND}/fmt/json The pattern must include {COMMAND} and must end with "/fmt/json".
mqttDevice.command.qos - An optional MQTT QoS value for commands. Defaults to 0.
mqttDevice.events.retain - Optional MQTT "retain" behavior for published events. Defaults to false.
mqttDevice.mqtt.clientId - Optional value to use for the MQTT clientId. Defaults to {mqttDevice.topic.prefix}id/{mqttDevice.id}.

[  
   {  
      "id":"libeliumSmartWater01",
      "latitude":53.290411,
      "longitude":-9.074406,
      "sensors":[  
         {  
            "id":"TemperatureSensorPt-1000",
            "type":"WaterMeter",
            "collection_time":30000,
            "publishing_time":60000
         },
         {  
            "id":"ConductivitySensor",
            "type":"WaterMeter",
            "collection_time":30000,
            "publishing_time":60000
         },
         {  
            "id":"DissolvedOxygenSensor",
            "type":"WaterMeter",
            "collection_time":30000,
            "publishing_time":60000
         },
         {  
            "id":"pHSensor",
            "type":"WaterMeter",
            "collection_time":30000,
            "publishing_time":60000
         },
         {  
            "id":"OxidationReductionPotentialSensor",
            "type":"WaterMeter",
            "collection_time":30000,
            "publishing_time":60000
         },
         {  
            "id":"TurbiditySensor",
            "type":"WaterMeter",
            "collection_time":30000,
            "publishing_time":60000
         }
      ]
   },
   {  
      "id":"libeliumSmartWaterIons01",
      "latitude":57.290411,
      "longitude":-8.074406,
      "sensors":[  
         {  
            "id":"NitriteNO2Sensor",
            "type":"WaterMeter",
            "collection_time":30000,
            "publishing_time":60000
         }
      ]
   }
]
